name = "open-property"
main = "src/server/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "open-property-db"
database_id = "local"

[vars]
KEYCLOAK_URL = "http://localhost:8080"
KEYCLOAK_REALM = "openproperty"
KEYCLOAK_CLIENT_ID = "openproperty-client"
KEYCLOAK_ENABLED = "true"
KEYCLOAK_REQUIRED = "false"
